Broken AuthFlow Additions (Token Response.)
Error: projects/oauth-oidc/src/oauth-service.ts(666,44): error TS2339: Property 'idToken' does not exist on type 'TokenResponse'.
projects/oauth-oidc/src/oauth-service.ts(667,49): error TS2339: Property 'id_token' does not exist on type 'TokenResponse'.